### PR TITLE
Dispose Process

### PR DESCRIPTION
**Pull request by nzdev**
System.Diagnostics.Process.GetCurrentProcess() creates a new Process instance that requires disposal.

PR disposes the created Process instance.

### CODE REVIEW

**Comment by Numpsy** [comment]
Change looks ok, no idea what happened to the CI build.

/Wonders if there's any value in using System.Environment.ProcessId where available?

**Comment by nzdev** [comment]
I would say so if targeting .net 5+.

**Review by Numpsy — APPROVED** [review]

**Comment by Numpsy** [comment]
@nblumhardt Any thoughts or objections to adding a net50 TFM?

**Comment by nblumhardt** [comment]
@Numpsy makes sense to me :+1:

**Comment by nblumhardt** [comment]
Not sure either what happened to CI, there - just something transient; kicked it off again, and all is now 🍏

**Pull request merged**
