### PR TITLE
Migrate the project file to SDK format

### PR DESCRIPTION
**Pull request by Numpsy**
Simply the result of running ```dotnet migrate```.

I was looking at adding a ```netstandard2.0``` target, but perhaps best done seperately afterwards?

(covers a bit of the same ground as the patch attached to #8)

### CODE REVIEW

**Comment by Numpsy** [comment]
Failed due to the CI build targetting a too old SDK :-(

**Comment by Numpsy** [comment]
Is it worth changing it to use PackageLicenseExpression instead of the URL at the same time?

**Comment by Numpsy** [comment]
@nblumhardt I'm not sure if anyone is watching this repository (the functionality is rather simple), but I see changes in other Serilog repositories adding extra targets to simplify the dependencies, so I think it's reasonable to update it. (I could also look at other build updates like PackageLicenceExpression, PackageIcon etc - not sure if it's better to do it all in one go, or in stages?)

**Comment by nblumhardt** [comment]
Hi @Numpsy ! "Watched" again now :-)

Yes, I think those updates would make sense, and the help would be appreciated. Is this PR ready for a final review/merged, or do you want to build upon it some more?

**Comment by Numpsy** [comment]
I was thinking to keep this one simple to just get it building with the current tools (my knowledge of appveyor etc is rather basic, so), and then do things like add the extra target framework and enable source link afterwards, so this is hopefully ok as is.

**Comment by nblumhardt** [comment]
Thanks! 😎

**Pull request merged**
